title: "dots"
status: "wip"
context:
    title: Ostia, estate a rischio, l'erosione ha "mangiato" il mare e distrutto le cabine
    subtitle: Con i romani Paolo Dieci, Pilar Buzzetti e Virginia Chimenti c'erano anche Joana Toole, Djordje Vdovic e Rosemary Mumbi che nella Capitale vivevano per motivi di lavoro
    imgsrc: http://placehold.it/300x149